// Copyright 2004-present Facebook. All Rights Reserved.

#ifndef QUANT_DECODE_OP_H_
#define QUANT_DECODE_OP_H_

#include "caffe2/core/context.h"
#include "caffe2/core/operator.h"

namespace caffe2 {

// Decode tensors based on given codebook,
// The codebook is generated by model_quantize.py
class QuantDecodeOp final : public Operator<CPUContext> {
 public:
  USE_OPERATOR_FUNCTIONS(CPUContext);
  QuantDecodeOp(const OperatorDef& operator_def, Workspace* ws)
      : Operator<CPUContext>(operator_def, ws) {}

  ~QuantDecodeOp() {}

  bool RunOnDevice() override;
};

} // namespace caffe2
#endif // QUANT_DECODE_OP_H_
